# Generated by Django 2.2 on 2019-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Me',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
