# Generated by Django 2.2 on 2019-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190606_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
