# Generated by Django 2.2 on 2019-08-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190817_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(default='salesforce', related_name='projects', to='projects.Category'),
        ),
    ]
