# Generated by Django 2.2 on 2019-08-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190817_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.Category'),
        ),
    ]
