# Generated by Django 2.2 on 2019-08-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
