# Generated by Django 2.2 on 2019-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_votes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author_comment',
            field=models.TextField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=999),
        ),
    ]
