# Generated by Django 2.2 on 2019-08-11 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20190803_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
