# Generated by Django 2.2 on 2019-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_playlist_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
