# Generated by Django 2.2 on 2019-08-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
