# Generated by Django 2.2 on 2019-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cta_landing',
            field=models.CharField(default='Create Your Box', max_length=100),
        ),
    ]
