# Generated by Django 2.2 on 2019-08-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_offer_cta_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='short_name',
            field=models.CharField(default='Curated Box', max_length=100),
        ),
    ]
